#!/bin/bash

if ! id "sddm" >/dev/null 2>&1; then
	groupadd -g 64 sddm 
	useradd  -c "sddm Daemon" -d /var/lib/sddm -u 64 -g sddm  -s /bin/false sddm
fi


if [ ! -f /tmp/foo.txt ]; then

sddm --example-config > /etc/sddm.conf

sed -i 's/-nolisten tcp//' /etc/sddm.conf
sed -i 's/none/on/' /etc/sddm.conf
sed -i 's/qtvirtualkeyboard//' /etc/sddm.conf

fi

systemctl enable sddm

cat > /etc/pam.d/sddm << "EOF" &&
# Begin /etc/pam.d/sddm

auth     requisite      pam_nologin.so
auth     required       pam_env.so

auth     required       pam_succeed_if.so uid >= 1000 quiet
auth     include        system-auth

account  include        system-account
password include        system-password

session  required       pam_limits.so
session  include        system-session

# End /etc/pam.d/sddm
EOF

cat > /etc/pam.d/sddm-autologin << "EOF" &&
# Begin /etc/pam.d/sddm-autologin

auth     requisite      pam_nologin.so
auth     required       pam_env.so

auth     required       pam_succeed_if.so uid >= 1000 quiet
auth     required       pam_permit.so

account  include        system-account

password required       pam_deny.so

session  required       pam_limits.so
session  include        system-session

# End /etc/pam.d/sddm-autologin
EOF

cat > /etc/pam.d/sddm-greeter << "EOF"
# Begin /etc/pam.d/sddm-greeter

auth     required       pam_env.so
auth     required       pam_permit.so

account  required       pam_permit.so
password required       pam_deny.so
session  required       pam_unix.so
-session optional       pam_systemd.so

# End /etc/pam.d/sddm-greeter
EOF
