PATH = /sbin:/bin:/usr/sbin:/usr/bin:/usr/libexec:/usr/sbin:/usr/libexec:/usr/sbin:/usr/libexec

PKG_LIST_DIR = basefile_dpkg glib_dpkg  libffi_dpkg make-ca_dpkg at-spi2-core_dpkg brotli_dpkg liboauth_dpkg p11-kit_dpkg xorg-server_dpkg xcb-util-wm_dpkg xorgproto_dpkg xcb-util-renderutil_dpkg xcb-util-cursor_dpkg mesa_dpkg 
PKG_LIST_DIR += acpid_dpkg rest_dpkg yaml_dpkg ruby_dpkg harfbuzz_dpkg SDL_dpkg libwebp_dpkg libwpe_dpkg wpebackend-fdo_dpkg enchant_dpkg openjpeg_dpkg 
PKG_LIST_DIR += links_dpkg lynx_dpkg libxml2_dpkg lightdm-gtk-greeter_dpkg amtk_dpkg gtksourceview4_dpkg tepl_dpkg libpeas_dpkg gspell_dpkg gedit_dpkg 
PKG_LIST_DIR += polkit_dpkg  gcr_dpkg gnome-keyring_dpkg extra-cmake-modules_dpkg sddm_dpkg librsvg_dpkg gdk-pixbuf_dpkg  libglade_dpkg gnome-shell_dpkg xscreensaver_dpkg xmlto_dpkg xdg-utils_dpkg gnome-online-accounts_dpkg gnome-control-center_dpkg

# не собираются sgml-common_dpkg  gnome-control-center_dpkg gcc_dpkg webkitgtk_dpkg   linux_dpkg 

export

all: ${PKG_LIST_DIR}

basefile_dpkg:
	${MAKE} -C basefile

glib_dpkg:
		${MAKE} -C glib	

gcc_dpkg:
		${MAKE} -C gcc	

libffi_dpkg:
		${MAKE} -C  libffi
			
linux_dpkg:
		${MAKE} -C linux	
					
make-ca_dpkg:
		${MAKE} -C make-ca

at-spi2-core_dpkg:
		${MAKE} -C at-spi2-core
		
brotli_dpkg:
		${MAKE} -C brotli		
		
sgml-common_dpkg:
		${MAKE} -C sgml-common		

liboauth_dpkg:
		${MAKE} -C liboauth				

polkit_dpkg:
		${MAKE} -C polkit			
		
p11-kit_dpkg:
		${MAKE} -C p11-kit			

acpid_dpkg:
		${MAKE} -C acpid		

extra-cmake-modules_dpkg:
		${MAKE} -C extra-cmake-modules

sddm_dpkg:
		${MAKE} -C sddm		

gcr_dpkg:
		${MAKE} -C gcr		

gnome-keyring_dpkg:
		${MAKE} -C gnome-keyring		

		
gnome-shell_dpkg:
		${MAKE} -C gnome-shell	


gnome-control-center_dpkg:
		${MAKE} -C gnome-control-center		
		
KDE_dpkg:
		${MAKE} -C KDE				
		
xorg-server_dpkg:
		${MAKE} -C xorg-server
		
xcb-util-wm_dpkg:
		${MAKE} -C xcb-util-wm
		
xorgproto_dpkg:
		${MAKE} -C xorgproto
		
xcb-util-renderutil_dpkg:
		${MAKE} -C xcb-util-renderutil
		
xcb-util-cursor_dpkg:
		${MAKE} -C xcb-util-cursor		
		
mesa_dpkg:
		${MAKE} -C mesa
		
rest_dpkg:
		${MAKE} -C rest	

yaml_dpkg:
		${MAKE} -C yaml

ruby_dpkg:
		${MAKE} -C ruby

harfbuzz_dpkg:
		${MAKE} -C harfbuzz

SDL_dpkg:
		${MAKE} -C SDL

libwebp_dpkg:
		${MAKE} -C libwebp

libwpe_dpkg:
		${MAKE} -C libwpe
		
wpebackend-fdo_dpkg:
		${MAKE} -C wpebackend-fdo

enchant_dpkg:
		${MAKE} -C enchant

openjpeg_dpkg:
		${MAKE} -C openjpeg

links_dpkg:
		${MAKE} -C links

lynx_dpkg:
		${MAKE} -C lynx

libxml2_dpkg:
		${MAKE} -C libxml2

libglade_dpkg:
		${MAKE} -C libglade

xmlto_dpkg:
		${MAKE} -C xmlto

xdg-utils_dpkg:
		${MAKE} -C xdg-utils

lightdm-gtk-greeter_dpkg:
		${MAKE} -C lightdm-gtk-greeter

amtk_dpkg:
		${MAKE} -C amtk

gtksourceview4_dpkg:
		${MAKE} -C gtksourceview4

tepl_dpkg:
		${MAKE} -C tepl


libpeas_dpkg:
		${MAKE} -C libpeas

gspell_dpkg:
		${MAKE} -C gspell

gedit_dpkg:
		${MAKE} -C gedit

xscreensaver_dpkg:
		${MAKE} -C xscreensaver

librsvg_dpkg:
		${MAKE} -C librsvg

gdk-pixbuf_dpkg:
		${MAKE} -C gdk-pixbuf

webkitgtk_dpkg:
		${MAKE} -C webkitgtk
		
		
		
gnome-online-accounts_dpkg:
		${MAKE} -C gnome-online-accounts			
						
				
								
