PATH = /sbin:/bin:/usr/sbin:/usr/bin:/usr/libexec:/usr/sbin:/usr/libexec:/usr/sbin:/usr/libexec

PKG_LIST_DIR = packaging  

#setuptools_scm Mako

export

all: ${PKG_LIST_DIR}


${PKG_LIST_DIR}:
	${MAKE} -C $@_dpkg
