#!/bin/bash


systemctl enable avahi-daemon

systemctl enable avahi-dnsconfd


if ! id "avahi" >/dev/null 2>&1; then
	groupadd -fg 84 avahi 
	useradd -c "Avahi Daemon Owner" -d /run/avahi-daemon -u 84 -g avahi -s /usr/bin/false avahi
	groupadd -fg 86 netdev
fi


