PATH = /sbin:/bin:/usr/sbin:/usr/bin:/usr/libexec:/usr/sbin:/usr/libexec:/usr/sbin:/usr/libexec

PKG_LIST_DIR = extra-cmake-modules_dpkg

# не собираются sgml-common_dpkg

export

all: ${PKG_LIST_DIR}

extra-cmake-modules_dpkg:
	${MAKE} -C extra-cmake-modules
		