#!/bin/bash


systemctl --global enable pipewire-pulse.socket

systemctl --global enable pipewire.socket


systemctl --global enable pipewire

systemctl --global enable pipewire-pulse

systemctl --global enable wireplumber


