#!/bin/bash

if [ ! -f /etc/pam.d/system-session ]; then

cat >> /etc/pam.d/system-session << "EOF"
# Begin Systemd addition

session  required    pam_loginuid.so
session  optional    pam_systemd.so

# End Systemd addition
EOF

fi

if [ ! -f /etc/pam.d/systemd-user ]; then

cat > /etc/pam.d/systemd-user << "EOF"
# Begin /etc/pam.d/systemd-user

account  required    pam_access.so
account  include     system-account

session  required    pam_env.so
session  required    pam_limits.so
session  required    pam_loginuid.so
session  optional    pam_keyinit.so force revoke
session  optional    pam_systemd.so

auth     required    pam_deny.so
password required    pam_deny.so

# End /etc/pam.d/systemd-user
EOF

fi

if ! id "systemd-timesync" >/dev/null 2>&1; then
	groupadd -fg 989 systemd-timesync 
	useradd -c "systemd timesync"  -u 989 -g systemd-timesync -s /usr/sbin/nologin systemd-timesync
	chown systemd-timesync:systemd-timesync  /var/lib/systemd/timesync
fi


systemctl daemon-reexec
