#!/bin/bash


mkdir -p  /etc/pam.d 

if [ ! -e /etc/pam.d/other ]; then
cat > /etc/pam.d/other << "EOF"
# Begin /etc/pam.d/other

auth        required        pam_warn.so
auth        required        pam_deny.so
account     required        pam_warn.so
account     required        pam_deny.so
password    required        pam_warn.so
password    required        pam_deny.so
session     required        pam_warn.so
session     required        pam_deny.so

# End /etc/pam.d/other
EOF
fi

chmod -v 4755 /usr/sbin/unix_chkpwd



if [ ! -e /etc/pam.d/system-account ]; then
cat > /etc/pam.d/system-account << "EOF" 
# Begin /etc/pam.d/system-account

account   required    pam_unix.so

# End /etc/pam.d/system-account
EOF
fi


if [ ! -e /etc/pam.d/system-auth ]; then
cat > /etc/pam.d/system-auth << "EOF" 
# Begin /etc/pam.d/system-auth

auth      required    pam_unix.so

# End /etc/pam.d/system-auth
EOF
fi

if [ ! -e /etc/pam.d/system-session ]; then
cat > /etc/pam.d/system-session << "EOF" 
# Begin /etc/pam.d/system-session

password  required    pam_unix.so   yescrypt shadow try_first_pass

# End /etc/pam.d/system-session
EOF
fi

if [ ! -e /etc/pam.d/system-password ]; then
cat > /etc/pam.d/system-password << "EOF"
# Begin /etc/pam.d/system-password

# use yescrypt hash for encryption, use shadow, and try to use any
# previously defined authentication token (chosen password) set by any
# prior module.
password  required    pam_unix.so       yescrypt shadow try_first_pass

# End /etc/pam.d/system-password
EOF
fi

