#!/usr/bin/bash



package() {

  local pkgroot ns dir
  for ns in -nons ''; do
    pkgroot="$PKG_BUILD_DIR_DPKG/usr/share/xml/docbook/xsl-stylesheets-$PKG_VERSION$ns"
    dir=$PGK_SOURCE_DIR/xsl/

    install -Dt "$pkgroot" -m644 $dir/VERSION{,.xsl}

    (
      shopt -s nullglob  # ignore missing files
      for fn in assembly common eclipse epub epub3 fo highlighting html \
        htmlhelp javahelp lib manpages params profiling roundtrip template \
        website xhtml xhtml-1_1 xhtml5
      do
        install -Dt "$pkgroot/$fn" -m644 $dir/$fn/*.{xml,xsl,dtd,ent}
      done
    )
  done

  install -d "$PKG_BUILD_DIR_DPKG/etc/xml"
  install -Dt "$PKG_BUILD_DIR_DPKG/usr/share/licenses/$PKG_NAME" -m644 $dir/COPYING
  
}  


package
